name: Tom Hollis Fine Furniture
favicon: null
layout_spectrum: 0.64307
typography_spectrum: 0.79112
title: Tom Hollis Fine Furniture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#becfdf'
    - '#ad5412'
    - '#c68453'
    - '#7d2904'
    - '#ddb196'
  brandStrength: 0.4375
  lightness: 0.5945961123798043
  saturation: 0.05703494418412447
  rhythmicContrast: 0.13053779629990458
purpose: []
